### ISSUE TITLE
kalliope_docker.conf file, getting invalid argument error when running image create command

### ISSUE THREAD

**Issue by jg8481it** [frnmst/kalliope-docker#1]
Hi,

Just an FYI. In the `kalliope_docker.conf` file when I use it as-is, then I run `./kalliope_docker.py image create` I get the following error back.

```
invalid argument "'kalliope-docker'" for "-t, --tag" flag: invalid reference format
```

I fixed this on my machine by changing the following line in the `kalliope_docker.conf` file.

Originally it was...
`Docker image tag = 'kalliope-docker'`

I removed the '' and changed it to the following...
`Docker image tag = kalliope-docker`

**Comment by frnmst** [comment]
Hello,

Thank you for reporing the issue. I guess that those extra quotes get parsed as part of the string. I am using a configuration file without that variable set, so it defaults to `kalliope-docker` wihout `''`. That's why I didn't see the problem before. 

Anyway, a fixed configuration file is available on the [master](https://github.com/frnmst/kalliope-docker/commit/bb206ce9778ed5b0bf8b58fe246c604df0410344) branch

**Comment by jg8481it** [comment]
Thanks for the reply and thank you for creating this repo. This is amazing work. I'm looking forward to using this.

**Comment by frnmst** [comment]
Good to hear that :)
